name: Docker Build -> Push -> Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Jar
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop spring-boot-ci-demo || true
            docker rm spring-boot-ci-demo || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest
            docker run -d --name spring-boot-ci-demo \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest
